name: Python FastAPI CI/CD

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Set up Python 3.9
      uses: actions/setup-python@v2
      with:
        python-version: '3.9'

    - name: Upgrade pip
      run: python -m pip install --upgrade pip

    - name: Install dependencies
      run: pip install -r requirements.txt

    # Uncomment and modify the following lines if you have tests to run
    # - name: Run tests
    #   run: |
    #     pytest

    - name: Deploy to Heroku
      if: github.ref == 'refs/heads/master' && success()
      uses: akhileshns/heroku-deploy@v3.12.12
      with:
        heroku_api_key: ${{ secrets.HEROKU_API_KEY }}
        heroku_app_name: "apicredit"
        heroku_email: "julien.caramanno@icloud.com"
